services:
  - type: web
    name: neuraforge-render
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TELEGRAM_TOKEN
        value: "8140846319:AAGQ_znQZFjMPMgS9l6uf0kWINkDC5ZvImY"
      - key: WEBHOOK_URL
        value: "https://neuraforge-render.onrender.com"
      - key: PORT
        value: "10000"
